### ISSUE TITLE
[EPIC] MVP Requirements

### ISSUE THREAD

**Issue by jsbrittain** [kraemer-lab/GRAPEVNE#245]
**P0 objectives:**
- [x] [STORY] Set workflows that will be supported (#250)
- [x] [STORY] User interface to access & use GRAPEVNE service (#251)
- [x] [STORY] Test run a workflow on dataset (#252)
- [x] [STORY] Notification - Workflow complete / error (#253)

**P1 objectives:**
- [ ] [STORY] Additional workflows that will be supported (#254)
  - _spec not clear_

**Added requirement:**
- [x] #311
