### ISSUE TITLE
[EPIC] V1 Launch

### ISSUE THREAD

**Issue by jsbrittain** [kraemer-lab/GRAPEVNE#291]
_This list is currently a placeholder / work-in-progress_

**V1 launch requirements**
This follow successful completion of MVP [#245].

**P0 objectives (critical to launch):**
- [ ] #243 
- [ ] #164 
- [ ] #103 
- [ ] #16 

**P1 objectives (desirable at launch):**
- [ ] #205 
- [ ] #290 
- [ ] #213 
- [ ] #278 
- [ ] #189 (pre-requisite to #146)
  - _breaks module compatibility; do this now [before v1?] or provide a route to support multiple snakemake versions afterwards? do modules need to be Snakemake version tagged?_
- [ ] #257 
- [ ] #277 

**P2 objectives (low priority, further time investment / prioritisation needed):**
- [ ] #255 
  - _Non-trivial. Dashboard would presumably require login, database, etc_
- [ ] #265 
  - _Sporadic, they usually pass on a re-run_
- [ ] #212 
  - _May be overkill as most components are standard MUI_
- [ ] #190 
  - _Chore_
- [ ] #157
  - _Low priority_
- [ ] #130
  - _No impact on builds, but upload sometimes reports a false-negative faliure_
- [ ] Embedded file browser
- [ ] Embedded terminal

**Pre-launch**
- [ ] Review all documentation
